sudo: required
language: generic

os:
  - osx
#  - linux

before_script: ./jvmw upgrade

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall java; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/versions; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update-reset && brew upgrade && brew cask upgrade; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install java6 java8 java java-beta; fi

script:
  - env
  - ./jvmw ./gradlew check