sudo: required
language: generic

os:
  - osx
#  - linux

before_script: ./jvmw upgrade

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall java; fi

script:
  - env
  - ./jvmw ./gradlew check