version: '{branch}.{build}'

image: Visual Studio 2017

platform: x64
configuration: Release

environment:
  ORACLE_USER: jvm.wrapper.itbasis@gmail.com
  ORACLE_PASSWORD:
    secure: C/g5UQyGDtB+FnJsj+fBLHQfOo6MrFVt7yDoHixRoIo=

init:
  - cmd: java -version
  - cmd: dir /w "C:\Program Files\Java\"

build: off

test_script:
  - cmd: gradlew clean check -i -s --no-daemon
