version: '{branch}.{build}'

image: Visual Studio 2017

platform: x64
configuration: Release

cache:
  - C:\Users\appveyor\.gradle

init:
  - cmd: java -version
  - cmd: dir /w "C:\Program Files\Java\"

build:
  verbosity: detailed

install:
  - cmd: gradlew clean -i --no-daemon

build_script:
  - cmd: gradlew clean assemble -s --no-daemon

test_script:
  - cmd: gradlew clean check -s --no-daemon
